spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:static/
agile:
  version: ${project.version}
  title: ${project.description}
#logging:
#  level:
#    cloud.agileframework: error