spring:
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        plain: "text/plain"
        xml: "application/xml"
        json: "application/json;charset=UTF-8"
      parameter-name: 'response-format'
    static-path-pattern: /static/**
    async:
      request-timeout: 3m
    locale-resolver: accept_header
    locale: zh
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-request-size: 1MB
      max-file-size: 2MB
      enabled: true
      file-size-threshold: 100KB
      location: 'temp'
  task:
    execution:
      pool:
        core-size: 8
      thread-name-prefix: '线程池-'
  resources:
    cache:
      cachecontrol:
        no-cache: true
      period: 604800
    static-locations: classpath:static/
server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
agile:
  version: ${project.version}
  title: ${project.description}