spring:
  kafka:
    consumer:
      group-id: monitor
      auto-offset-reset: latest
      bootstrap-servers: ip1:9092,ip2:9092,ip3:9092
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ip1:9092,ip2:9092,ip3:9092p
      acks: all
      retries: 3
      buffer-memory: 40960
      batch-size: 4096
    template:
      default-topic: nwbs-eval-task
    listener:
      poll-timeout: 30000
