agile:
  version: ${project.version}
  title: ${project.description}
  module-name: 'sys'
  mail:
    server-host: 123
    server-port: 8249
    server-default-from: mydeathtrial@163.com
  generator:
    entity-prefix: ''
    entity-suffix: Entity
    entity-url: D:\workspace-idss\agile\src\main\java\com\agile\mvc\entity1
    service-prefix: ''
    service-suffix: Service
    service-url: D:\workspace-idss\agile\src\main\java\com\agile\mvc\service
    test-prefix: ''
    test-suffix: ServiceTest
    test-url: D:\workspace-idss\agile\test\main\java\com\agile\mvc\service
    table-name: 'sys_task'
  kaptcha:
    enable: true
    token-header: authCode
    border: 'no'
    border-color: 45,45,45
    image-height: 45
    image-width: 125
    textproducer-char-length: 4
    textproducer-font-color: 255,255,255
    textproducer-font-names: 宋体,楷体,微软雅黑
    textproducer-font-size: 40
    live-time: 180
    url: /api/authcode
    text:
  log:
    package-uri: ${LOCAL_LOGS_PATH:-logs}/
    trigger-type: size
    trigger-value: 1M
    package-name:
      com.agile: info,error,debug
      org.springframework: info,error,debug
      com.idss: info,error,debug
  security:
    enable: true
    exclude-url: /swagger-ui.html,/webjars/springfox-swagger-ui/*,/v2/api-docs,/swagger-resources/**
    login-out-url: /api/logout
    login-url: /api/login
    login-username: userName
    login-password: password
    verification-code: authCode
    token-timeout: 30m
    token-header: authToken
    token-secret: 23617641641
    login-error-count: 5
    login-error-timeout: 2m
    login-lock-time: 1m
  cors:
    allow-credentials: true
    allow-headers: Content-Type,X-CSRF-TOKEN,JSESSIONID
    allow-methods: GET,POST,PUT,DELETE,OPTIONS,JSONP
    allow-origin: '*'
  task:
    enable: true
  swagger:
    enable: true
    title: Agile 平台API文档
    description: 这是个不错的文档
    terms-of-service-url: http://www.baidu.com
    version: ${project.version}
