agile:
  version: ${project.version}
  title: ${project.description}
  module-name: 'sys'
  kaptcha:
    enable: true
    token-header: authCode
    border: 'no'
    border-color: 45,45,45
    image-height: 45
    image-width: 125
    textproducer-char-length: 4
    textproducer-font-color: 255,255,255
    textproducer-font-names: 宋体,楷体,微软雅黑
    textproducer-font-size: 40
    live-time: 180
    url: /api/authcode
    text:
  log:
    package-uri: ${LOCAL_LOGS_PATH:-logs}/
    trigger-type: size
    trigger-value: 5M
    levels: debug,info,error
    business-log: true
    package-name:
      com.agile: info,error,debug
      org: error
      com: error
      io: error
      javax: error
      net: error
    timeout: 1d
    max-size: 200M
    custom-log: true
  security:
    enable: true
    exclude-url: /swagger-ui.html,/webjars/springfox-swagger-ui/*,/v2/api-docs,/swagger-resources/**,/api/password-find
    login-out-url: /api/logout
    login-url: /api/login
    login-username: userName
    login-password: password
    verification-code: authCode
    token-timeout: 30m
    token-header: authToken
    token-secret: 23617641641
    password:
      strength: 5
      duration: 31d
      aes-key: idssinsightkey01
      aes-offset: 3612213421341234
      algorithm-model: 'AES/CBC/PKCS5Padding'
      lock-for-expiration: true
      strength-conf:
        weight-of-key-words:
          - password
          - iloveyou
          - sunshine
          - 1314
          - 520
          - a1b2c3
          - admin
        weight-of-regex-map[0]:
          # 单字符 三至多次重复 aaa bbb ccccc
          regex: '(?:([\\da-zA-Z])\\1{2,})'
          weight: 0.4
        weight-of-regex-map[1]:
          # 双至多重字符段 重复 aabbcc aaabbbccc
          regex: '(?:([\\da-zA-Z])\\1+){2,}'
          weight: 0.15
        weight-of-regex-map[2]:
          # 二至多字符段 重复 abab abcabc
          regex: '([\\da-zA-Z]{2,})\\1+'
          weight: 0.12
        weight-of-regex-map[3]:
          # 至少三位递增顺/逆数 123 567 3456
          regex: '((?:0(?=1)|1(?=2)|2(?=3)|3(?=4)|4(?=5)|5(?=6)|6(?=7)|7(?=8)|8(?=9)){2,}+\\d)|((?:9(?=8)|8(?=7)|7(?=6)|6(?=5)|5(?=4)|4(?=3)|3(?=2)|2(?=1)|1(?=0)){2,}+\\d)'
          weight: 0.2
        weight-of-regex-map[4]:
          # 至少三位递增顺字母 abc bcde
          regex: '((?:a(?=b)|b(?=c)|c(?=d)|d(?=e)|e(?=f)|f(?=g)|g(?=h)|h(?=i)|i(?=j)|j(?=k)|k(?=l)|l(?=m)|m(?=n)|n(?=o)|o(?=p)|p(?=q)|q(?=r)|r(?=s)|s(?=t)|t(?=u)|u(?=v)|v(?=w)|w(?=x)|x(?=y)|y(?=z)){2,}+[a-z])|((?:A(?=B)|B(?=C)|C(?=D)|D(?=E)|E(?=F)|F(?=G)|G(?=H)|H(?=I)|I(?=J)|J(?=K)|K(?=L)|L(?=M)|M(?=N)|N(?=O)|O(?=P)|P(?=Q)|Q(?=R)|R(?=S)|S(?=T)|T(?=U)|U(?=V)|V(?=W)|W(?=X)|X(?=Y)|Y(?=Z)){2,}+[A-Z])'
          weight: 0.18
        weight-of-regex-map[5]:
          # 至少三位递增顺键盘字母 qwe rtyu
          regex: '((?:q(?=w)|w(?=e)|e(?=r)|r(?=t)|t(?=y)|y(?=u)|u(?=i)|i(?=o)|o(?=p)){2,}+[a-z])|((?:Q(?=W)|W(?=E)|E(?=R)|R(?=T)|T(?=Y)|Y(?=U)|U(?=I)|I(?=O)|O(?=P)){2,}+[A-Z])|((?:a(?=s)|s(?=d)|d(?=f)|f(?=g)|g(?=h)|h(?=j)|j(?=k)|k(?=l)){2,}+[a-z])|((?:A(?=S)|S(?=D)|D(?=F)|F(?=G)|G(?=H)|H(?=J)|J(?=K)|K(?=L)){2,}+[A-Z])|((?:z(?=x)|x(?=c)|c(?=v)|v(?=b)|b(?=n)|n(?=m)){2,}+[a-z])|((?:Z(?=X)|X(?=C)|C(?=V)|V(?=B)|B(?=N)|N(?=M)){2,}+[A-Z])'
          weight: 0.1
        weight-of-regex-map[6]:
          # 日期
          regex: '((((19|20)\\d{2})-(0?[13-9]|1[012])-(0?[1-9]|[12]\\d|30))|(((19|20)\\d{2})-(0?[13578]|1[02])-31)|(((19|20)\\d{2})-0?2-(0?[1-9]|1\\d|2[0-8]))|((((19|20)([13579][26]|[2468][048]|0[48]))|(2000))-0?2-29))'
          weight: 0.3
        weight-of-regex: 0.65
        weight-of-key-word: 0.35
        max-length: 32
    error-sign:
      max-error-count: 5
      error-sign-lock-time: 2m
      error-sign-count-timeout: 1m
      enable: false
  cors:
    allow-credentials: true
    allow-headers: Content-Type,X-CSRF-TOKEN,JSESSIONID
    allow-methods: GET,POST,PUT,DELETE,OPTIONS,JSONP
    allow-origin: '*'
  task:
    enable: false
  swagger:
    enable: true
    title: Agile 平台API文档
    description: 这是个不错的文档
    terms-of-service-url: http://www.baidu.com
    version: ${project.version}
  dictionary:
    enable: true
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration,org.springframework.boot.autoconfigure.webservices.client.WebServiceTemplateAutoConfiguration,org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration,org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration,org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration,org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration,org.springframework.boot.actuate.autoconfigure.metrics.export.elastic.ElasticMetricsExportAutoConfiguration,org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration,org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthIndicatorAutoConfiguration