spring:
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      shutdown-timeout: 100
    ssl: false
    database: 0
    timeout: 5000
#    url:
#    哨兵模式
#    sentinel:
#      master:
#      nodes:
#    集群模式
#    cluster:
#      max-redirects:
#      nodes: