agile:
  druid:
    data-base-ip: 127.0.0.1
    data-base-name: agile_db
    data-base-port: 3306
    username: root
    password: 123456
    # 最大连接数
    max-active: 100
    max-pool-prepared-statement-per-connection-size: 20
    # 获取连接时最大等待5秒，单位毫秒
    max-wait: 5000
    # 30分钟后未使用，则清除空闲连接，单位毫秒
    min-evictable-idle-time-millis: 1800000
    use-global-data-source-stat: true
    # 初始化时建立物理连接的个数
    initial-size: 1
    # 最小连接池数量
    min-idle: 1
    # 是否缓存preparedStatement，也就是PSCache
    pool-prepared-statements: false
    remove-abandoned: true
    remove-abandoned-timeout: 300000
    # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    time-between-eviction-runs-millis: 20000
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    test-on-borrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    test-on-return: false
    # 建议配置为true，不影响性能，并且保证安全性,申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    manager-name: admin
    manager-password: admin
    reset-enable: true
    session-stat-max-count: 100000
    dashboard-url: /druid
    data-base-url-param: 'serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL'
    type: mysql
    connection-error-retry-attempts: 10
    url: jdbc:mysql://${agile.druid.data-base-ip}:${agile.druid.data-base-port}/${agile.druid.data-base-name}?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&allowPublicKeyRetrieval=true