agile:
  druid:
    data-base-ip: 192.168.200.105
    data-base-name: guosen_two_db
    data-base-port: 3306
    username: root
    password: guosen0211
    max-active: 100
    max-pool-prepared-statement-per-connection-size: 20
    max-wait: 60000
    min-evictable-idle-time-millis: 300000
    use-global-data-source-stat: true
    initial-size: 1
    min-idle: 1
    pool-prepared-statements: true
    remove-abandoned: true
    remove-abandoned-timeout: 300000
    time-between-eviction-runs-millis: 60000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    manager-name: admin
    manager-password: admin
    reset-enable: true
    session-stat-max-count: 100000
    dashboard-url: /druid
    data-base-url-param: 'serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL'
    type: mysql
