spring:
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://${agile.druid.data-base-ip}:${agile.druid.data-base-port}/${agile.druid.data-base-name}?${agile.druid.data-base-url-param}
    username: ${agile.druid.username}
    password: ${agile.druid.password}
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: ${agile.druid.initial-size}
      min-idle: ${agile.druid.min-idle}
      maxActive: ${agile.druid.max-active}
      # 配置获取连接等待超时的时间
      maxWait: ${agile.druid.max-wait}
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: ${agile.druid.time-between-eviction-runs-millis}
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: ${agile.druid.min-evictable-idle-time-millis}
      validationQuery: SELECT 1
      testWhileIdle: ${agile.druid.test-while-idle}
      testOnBorrow: ${agile.druid.test-on-borrow}
      testOnReturn: ${agile.druid.test-on-return}
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: ${agile.druid.max-pool-prepared-statement-per-connection-size}
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: ${agile.druid.exclusions}
        session-stat-max-count: ${agile.druid.session-stat-max-count}
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: ${agile.druid.dashboard-url}/*
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: ${agile.druid.reset-enable}
        # 登录名
        login-username: ${agile.druid.manager-name}
        # 登录密码
        login-password: ${agile.druid.manager-password}
        # 开关
        enabled: true
      connection-error-retry-attempts: ${agile.druid.connection-error-retry-attempts}
      aop-patterns: com.agile.mvc.service.*
      filter:
        wall:
          config:
            select-where-alway-true-check: false
          enabled: false
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        slf4j:
          enabled: true
          data-source-log-enabled: true
          connection-log-enabled: true
          statement-log-enabled: true
          result-set-log-enabled: true
        config:
          enabled: true
