agile:
  version: ${project.version}
  title: ${project.description}
  mail:
    server-host: 123
    server-port: 8249
    server-default-from: mydeathtrial@163.com
  cache:
    proxy: ehcache
  generator:
    entity-prefix: ''
    entity-suffix: Entity
    entity-url: D:\workspace-idss\agile\src\main\java\com\agile\mvc\entity
    service-prefix: ''
    service-suffix: Service
    service-url: D:\workspace-idss\agile\src\main\java\com\agile\mvc\service
    test-prefix: ''
    test-suffix: ServiceTest
    test-url: D:\workspace-idss\agile\test\main\java\com\agile\mvc\service
    table-name: 'sys_authorities,sys_bt_%,sys_login,sys_resources,sys_roles,sys_users,log_%,dictionary_%'
  ehcache:
    max-entries-local-heap: 10000
    max-entries-local-disk: 10000000
    time-to-idle: 120
    time-to-live: 120
    disk-spool-buffer-size: 30
    blocking: false
    eternal: false
    memory-store-eviction-policy: LFU
    disk-expiry-thread-interval-seconds: 120
  kaptcha:
    enable: true
    token-header: authCode
    border: 'no'
    border-color: black
    image-height: 45
    image-width: 125
    textproducer-char-length: 4
    textproducer-font-color: black
    textproducer-font-names: 宋体,楷体,微软雅黑
    textproducer-font-size: 40
    live-time: 60
    url: /api/authcode
    text:
  log:
    package-uri: ${LOCAL_LOGS_PATH:-logs}/
    trigger-type: size
    trigger-value: 1M
    package-name:
      org.springframework: info,error
  redis:
    host: 127.0.0.1
    max-idle: 300
    max-wait-millis: 1000
    min-idle: 0
    pass: ''
    port: 6379
    test-on-borrow: true
    test-on-return: false
    duration: 30
  security:
    enable: false
    exclude-url: /test,/test2,/swaggerInfo*,/api/test/test*,/swagger-ui.html
    login-out-url: /api/logout
    login-url: /api/login
    login-username: userName
    login-password: password
    verification-code: authCode
    token-key: 23617641641
    token-timeout: 1800
    token-header: authToken
  cors:
    allow-credentials: true
    allow-headers: Content-Type,X-CSRF-TOKEN,JSESSIONID
    allow-methods: GET,POST,PUT,DELETE,OPTIONS,JSONP
    allow-origin: '*'
  task:
    enable: false
  elasticsearch:
    enable: false
    cluster-name: argus
    cluster-nodes: 192.168.200.94:39390,192.168.200.95:39390
    cluster-hosts: 192.168.200.94:39390
    pool-size: 5
    index-date-format: yyyyMMdd
    time-field: create_time
    id-field: id
    raw-msg-filed: raw_msg
    scroll-time-value: 60000
    scroll-set-size: 30000
  swagger:
    enable: true
    title: Agile 平台API文档
    description: 这是个不错的文档
    terms-of-service-url: http://www.baidu.com
    version: ${project.version}