spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
csp:
  sentinel:
    dashboard:
      server: localhost:8080
management:
  endpoints:
    web:
      exposure:
        #\u52A0\u8F7D\u6240\u6709\u7684\u7AEF\u70B9\uFF0C\u9ED8\u8BA4\u53EA\u52A0\u8F7D\u4E86info\u3001health
        include: '*'
  endpoint:
    health:
      show-details: always
    #\u53EF\u4EE5\u5173\u95ED\u6307\u5B9A\u7684\u7AEF\u70B9
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
feign:
  sentinel:
    enabled: true
