agile:
  elasticsearch:
    enable: true
    config:
      a1:
        indexDateFormat: yyyyMMdd
        timeField: create_time
        idField: id
        rawMsgFiled: raw_msg
        clusterName: idss-guosen2
        clusterNodes: 192.168.200.104:9300,192.168.200.105:9300,192.168.200.106:9300,192.168.200.107:9300
        clusterHosts: 9200
        scrollTimeValue: 60000
        scrollSetSize: 30000
      a2:
        indexDateFormat: yyyyMMdd
        timeField: create_time
        idField: id
        rawMsgFiled: raw_msg
        clusterName: idss-guosen2
        clusterNodes: 192.168.200.104:9300,192.168.200.105:9300,192.168.200.106:9300,192.168.200.107:9300
        clusterHosts: 9200
        scrollTimeValue: 60000
        scrollSetSize: 30000