agile:
  version: ${project.version}
  title: ${project.description}
  module-name: 'sys'
  mail:
    server-host: 123
    server-port: 8249
    server-default-from: mydeathtrial@163.com
  cache:
    proxy: redis
  generator:
    entity-prefix: ''
    entity-suffix: Entity
    entity-url: D:\workspace-idss\agile\src\main\java\com\agile\mvc\entity
    service-prefix: ''
    service-suffix: Service
    service-url: D:\workspace-idss\agile\src\main\java\com\agile\mvc\service
    test-prefix: ''
    test-suffix: ServiceTest
    test-url: D:\workspace-idss\agile\test\main\java\com\agile\mvc\service
    table-name: 'sys_login'
  ehcache:
    max-entries-local-heap: 10000
    max-entries-local-disk: 10000000
    time-to-idle: 0
    time-to-live: 0
    disk-spool-buffer-size: 30
    blocking: false
    eternal: true
    memory-store-eviction-policy: LFU
    disk-expiry-thread-interval-seconds: 120
  kaptcha:
    enable: true
    token-header: authCode
    border: 'no'
    border-color: black
    image-height: 45
    image-width: 125
    textproducer-char-length: 4
    textproducer-font-color: black
    textproducer-font-names: 宋体,楷体,微软雅黑
    textproducer-font-size: 40
    live-time: 60
    url: /api/authcode
    text:
  log:
    package-uri: ${LOCAL_LOGS_PATH:-logs}/
    trigger-type: size
    trigger-value: 1M
    package-name:
      org.springframework: info,error,debug
      com.idss.common.datafactory: info,error,debug
  redis:
    host: 127.0.0.1
    max-idle: 300
    max-wait-millis: 1000
    min-idle: 0
    pass: ''
    port: 6379
    test-on-borrow: true
    test-on-return: false
    duration: 30
  security:
    enable: false
    exclude-url: /test,/test2,/swaggerInfo*,/api/test/test*,/swagger-ui.html
    login-out-url: /api/logout
    login-url: /api/login
    login-username: userName
    login-password: password
    verification-code: authCode
    token-timeout: 1800
    token-header: authToken
    token-secret: 23617641641
  cors:
    allow-credentials: true
    allow-headers: Content-Type,X-CSRF-TOKEN,JSESSIONID
    allow-methods: GET,POST,PUT,DELETE,OPTIONS,JSONP
    allow-origin: '*'
  task:
    enable: false
  swagger:
    enable: true
    title: Agile 平台API文档
    description: 这是个不错的文档
    terms-of-service-url: http://www.baidu.com
    version: ${project.version}
eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id:${server.port}}
    metadata-map:
      management:
        port: ${management.port}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:9090/eureka/
    healthcheck:
      enabled: true
